Localization "Joining the team" page updates
ScratchAddons/website-v2 pull request #111
Opened 2021-08-27 15:59 UTC by thecrewmate876

These are some small updates such as making the list of already translated languages up-to-date.
@WorldLanguages

2021-08-28 14:39 UTC, WorldLanguages commented
I'm not sure, but at some point I thought this page shouldn't ever be translated, because you need to know basic English in order to translate anyway.

2021-08-29 11:52 UTC, thecrewmate876 commented on content/docs/localization/joining-the-localization-team.md
> +You'll soon be accepted into the Transifex team and you'll get email notifications when there's new strings to translate.
> `there are` rather than `there's` now it's plural?

@pufferfish101007 oops i forgot

2021-08-29 11:54 UTC, thecrewmate876 commented on content/docs/localization/joining-the-localization-team.md
> +You'll soon be accepted into the Transifex team and you'll get email notifications when there's new strings to translate.
resloved in [`0cb895c` (#111)](https://github.com/ScratchAddons/website-v2/pull/111/commits/0cb895cfdc1d83fde205b9406d124536c2bbf00f)

2021-08-29 11:55 UTC, thecrewmate876 commented
> I'm not sure, but at some point I thought this page shouldn't ever be translated, because you need to know basic English in order to translate anyway.

@WorldLanguages I'm not translating the page.

2021-08-29 14:23 UTC, WorldLanguages commented
lol right 🤦‍♂️

2021-09-19 13:00 UTC, GrahamSH-LLK requested changes
Looks good, just 1 nit

2021-09-19 13:00 UTC, GrahamSH-LLK commented on content/docs/localization/joining-the-localization-team.md
> +d---
This looks accidental

2021-09-23 19:15 UTC, merged