Create blog post for v1.37.0
ScratchAddons/website-v2 pull request #431
Opened 2024-03-30 02:03 UTC by DNin01

Resolves #429

2024-03-30 02:03 UTC, DNin01 commented on content/blog/v1-37-released.md
> +date: 2024-03-30T00:00:00Z
Date TBD but will probably be correct by the time we merge anyway.

2024-03-30 10:59 UTC, Hans5958 commented on content/blog/v1-37-released.md
> +# What's new in Scratch Addons v1.37.0
Remove this heading. The title on the front matter will be used instead.

2024-03-30 11:00 UTC, Hans5958 requested changes
For some reason I have to fill this before I can press "Request changes." Maybe there's an issue on Refined GitHub? In any case, please take a look on my previous review.

2024-03-31 11:18 UTC, Hans5958 approved these changes
Any issues, @WorldLanguages?

2024-03-31 14:39 UTC, WorldLanguages approved these changes

2024-03-31 14:39 UTC, merged