Revert "Add Pre-send warning for 1.38.1 bug"
ScratchAddons/website-v2 pull request #454
Opened 2024-06-04 18:02 UTC by WorldLanguages

Reverts ScratchAddons/website-v2#450

Version 1.38.2 fixed this issue, so within a few days this pre-send warning doesn't make sense anymore.

2024-06-04 19:08 UTC, Samq64 approved these changes

2024-06-05 01:01 UTC, Hans5958 requested changes
Holding until v1.39.0 (see [the relevant section on the docs](https://github.com/ScratchAddons/website-v2/wiki/Feedback-presend-warning#removing-a-warning)).

2024-06-05 01:10 UTC, WorldLanguages commented
Technically the next minor release was already released :P 

I would recommend removing the warning a few days from now, as most people will be getting the update

2024-06-05 01:39 UTC, Hans5958 commented
Minor release = v1.39.0 (following SemVer here)

I remember the lines that Chrome users are quite slow at adopting the updates (Chromebook users?), so it is why this has to hold a bit.

2024-08-28 01:43 UTC, merged