Create blog post for release v1.39
ScratchAddons/website-v2 pull request #490
Opened 2024-08-28 20:55 UTC by DNin01

This is the blog post that will go along with [Scratch Addons v1.39.0](https://github.com/ScratchAddons/ScratchAddons/releases/tag/v1.39.0).

2024-08-28 20:56 UTC, DNin01 commented on content/blog/v1-39-released.md
> +date: null # TBD
Specify this before merging.

2024-08-29 02:38 UTC, Hans5958 requested changes

2024-08-29 02:38 UTC, Hans5958 commented on content/blog/v1-39-released.md
> +# What's new in Scratch Addons v1.39.0
Remove this. Title goes to the front matter.

```suggestion
```

2024-08-29 02:38 UTC, Hans5958 commented on content/blog/v1-39-released.md
> +### 📄 Choose what to do with conflicting asset names
Use the second-level heading as it is for semantics, not for heading font size reasons (also true to later headings).

```suggestion
## 📄 Choose what to do with conflicting asset names
```

2024-08-29 02:40 UTC, Hans5958 commented on content/blog/v1-39-released.md
> +### 📄 Choose what to do with conflicting asset names
I have to fix this with the previous posts later. For this post, this can be done now.

2024-08-30 18:23 UTC, DNin01 commented
All good now, @Hans5958?

2024-08-30 18:40 UTC, WorldLanguages commented
@Hans5958 Blocking merge due to those things is a bit harsh 😅 You can also review without going red

2024-08-30 18:40 UTC, WorldLanguages commented on content/blog/v1-39-released.md
> +date: null # TBD
```suggestion
date: 2024-08-31
```

2024-08-31 17:13 UTC, Hans5958 approved these changes

2024-08-31 18:48 UTC, merged